# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Green Team Project
email: Mtuck@una.edu
description: > # this means to ignore newlines until "baseurl:"
	This project will host all of green teams documents for CS455. 
baseurl: "/455Project" # the subpath of your site, e.g. /blog
url: "http://mtuck.github.io" # the base hostname & protocol for your site
twitter_username: Mtuck
github_username:  Mtuck
# Build settings
markdown: kramdown
